### ISSUE TITLE
bs-Properties are not supported in type definitions

### ISSUE THREAD

**Issue by geepy** [react-bootstrap/react-bootstrap-typescript#5]
I am trying to convert my bootstrap-react app to TypeScript. Almost everything works fine, but all of the "bs" attributes are not present in the type definitions.
I regularly use "bsClass" and "bsSize" on all react-bootstrap controls, but I get an "property does not exist" error from the ts compiler.
How would I go for that?

Guenter

**Comment by iamsaksham** [comment]
Any update on this issue?? I am facing the same problem

**Comment by iamsaksham** [comment]
@christhomas bsClass for button is missing, I added that and created a pull request #12 Please verify and merge it asap.

**Comment by christhomas** [comment]
its merged

**Comment by christhomas** [comment]
you should find a new npm module now, with version 0.0.9

**Comment by iamsaksham** [comment]
cool, why not close this issue for now?
